In [2]:
import initialize

In [3]:
import sample
sample.message

'This is "/Users/wakita/Library/CloudStorage/Dropbox/projects/project_template/src/sample/__init__.py".'

In [ ]:
import os
print(os.environ['HOME'])

os.chdir('..')
print(os.getcwd())

hoge
/Users/wakita/Library/CloudStorage/Dropbox/projects/project_template

In [12]:
from sample.spi import get_spi_data

df = get_spi_data(year=2023)
df

,Country,SPI country code,Social Progress Index,Basic Needs,Foundations of Wellbeing,Opportunity,Nutrition and Medical Care,Water and Sanitation,Housing,Safety,...,Satisfied demand for contraception (% satisfied demand),Equal access index (0=low; 1=high),Acceptance of gays and lesbians (proportion of pop.),Count on help (proportion of pop.),Discrimination and violence against minorities (0=low discrimination; 10=high discrimination),Academic freedom (0=low; 1=high),Women with advanced education (proportion of females),"Citable documents (documents/1,000 people)",Quality weighted universities (points),GDP per capita (constant 2017 international dollars)
0,World,WWW,63.44,77.04,61.52,51.76,77.04,79.23,80.34,71.55,...,75.1068,0.5217,0.415,0.7481,6.966,0.4415,0.3417,0.5900,71.9266,17175.3516
13,Afghanistan,AFG,32.15,53.19,30.26,13.00,46.27,66.46,58.44,41.58,...,48.3000,0.0230,0.030,0.3400,8.300,0.1360,0.0552,0.0152,26.2195,1517.0162
26,Albania,ALB,71.70,86.57,73.80,54.73,91.05,83.03,90.13,82.09,...,9.5000,0.6920,0.105,0.7050,3.500,0.8200,0.3836,0.3383,20.5386,15501.6629
39,Algeria,DZA,64.22,80.93,63.11,48.61,87.76,78.15,87.28,70.53,...,72.8000,0.6470,NaN,0.7800,7.000,0.2290,0.2783,0.2313,56.9038,11187.3823
52,Angola,AGO,43.90,52.84,44.84,34.01,56.53,38.05,56.42,60.36,...,30.8000,0.4950,NaN,NaN,8.700,0.4540,0.1035,0.0057,16.8758,5906.1157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2496,St. Lucia,LCA,NaN,80.43,NaN,NaN,83.29,85.88,89.44,63.12,...,76.3000,NaN,NaN,NaN,NaN,NaN,0.3421,0.0945,NaN,15037.7619
2509,St. Vincent and the Grenadines,VCT,NaN,81.42,NaN,NaN,85.68,87.73,89.12,63.16,...,81.9000,NaN,NaN,NaN,NaN,NaN,0.2521,0.2309,NaN,14572.6555
2522,Taiwan,TWN,NaN,NaN,NaN,78.97,NaN,NaN,NaN,86.11,...,84.0000,0.8840,0.585,0.8550,NaN,0.8450,0.7230,1.8953,83.1594,NaN
2535,Tonga,TON,NaN,76.56,NaN,NaN,79.62,89.94,85.48,51.21,...,48.8000,NaN,NaN,NaN,NaN,NaN,0.4065,0.2433,NaN,6142.9634
2548,Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,NaN,84.95,NaN,...,43.7000,NaN,NaN,NaN,NaN,NaN,0.3006,0.2652,NaN,4591.3307

In [ ]:
df.to_csv('out/spi.csv', index=False)